### ISSUE TITLE
Add generic script to generate docs in repository and add setup info in Readme.md

### ISSUE THREAD

**Issue by mariobehling** [fossasia/yaydoc#1]
Add generic script to generate docs in repository and add setup info in Readme.md. Follow set up as used in loklak and SUSI.AI server project.

**Comment by sch00lb0y** [comment]
@mariobehling i'll would like to work on this

**Comment by sch00lb0y** [comment]
I have made the script [](https://github.com/sch00lb0y/yaydoc). please check and let me know.
