### ISSUE TITLE
Unify the main generate script and the webUI/generate script

### ISSUE THREAD

**Issue by pri22296** [fossasia/yaydoc#108]
### Current behaviour

there are two generate scripts which would be difficult to maintain.

### Expected behaviour

there should be a single generate script.

**Comment by imujjwal96** [comment]
Since the generate script of the webui is constantly being updated with the inclusion of each feature, I think now would not be the perfect time to unify these two. Maybe we should postpone it to a later stage in development.
Can we tag this issue with a "Low priority" label or "Postponed" label?

**Comment by pri22296** [comment]
sounds good. could you add an appropriate label to this issue?

**Comment by imujjwal96** [comment]
> Also since the user would be interacting with yaydoc via webUI, do we still need the travis implementation?

Deserves it's own issue for discussion. 
Raise one, would you?

**Comment by pri22296** [comment]
This is how i'm planning to solve this issue:
- Preserve the arguments based approach in `generate.2.sh`.
- Create a wrapper script for travis that just reads enviornment variables and uses it to call `generate.2.sh`
- Modify `config.py` such that, All variables which are not defined or are set as `""`, would have the defaults assigned to them or if a `.yaydoc.yml` is present, values would be read from there.
- have the `generate.2.sh` take an additional argument that determines if the script is executed from webUI or from the travis wrapper script. use this to perform any operations which only need to be done on the webUI or Travis.

@imujjwal96 sounds good? any suggestions?

**Comment by imujjwal96** [comment]
> Modify config.py such that, All variables which are not defined or are set as "", would have the defaults assigned to them or if a .yaydoc.yml is present, values would be read from there.

Priority order?
