### ISSUE TITLE
remove the cloned repository after documentaion get generated.

### ISSUE THREAD

**Issue by sch00lb0y** [fossasia/yaydoc#113]
### This is a
- [x] Bug report
- [ ] Feature request

### Current behaviour

now repository is clonned and kept inside the temp folder, even after documentation get generated. since we'll be running on servers it'll occupy more space if it is big repository
### Expected behaviour

remove the clonned repository once documentation get generated

### Steps to reproduce
1.
2.
3.

**Comment by imujjwal96** [comment]
Apart from occupying space, it will also cause more troubles. The repository is cloned with the same directory name at each execution. So a user cannot create documentation of a script more than once.

**Comment by pri22296** [comment]
@imujjwal96 Is that still the case? uuidv4 should be unique for each build right?
