### ISSUE TITLE
deploy webui to heroku

### ISSUE THREAD

**Issue by sch00lb0y** [fossasia/yaydoc#119]
### This is a
- [ ] Bug report
- [x] Feature request

### Current behaviour

WEBUI is not deployed anywhere
### Expected behaviour

deploy the webui to heroku and make it auto-deployable.

### Steps to reproduce
1.
2.
3.

**Comment by imujjwal96** [comment]
Are you sure it isn't?
The last time i checked, i deployed it

**Comment by imujjwal96** [comment]
In fact i even shared it in the gitter chat

**Comment by sch00lb0y** [comment]
I agree with you @imujjwal96. intially you deployed the github oauth implementaion.can you delpoy the current version of webui and update the readme ?

**Comment by imujjwal96** [comment]
Sure.
