### ISSUE TITLE
Implement way to directly generate a sphinx documenation site with md files instead of rst files

### ISSUE THREAD

**Issue by mariobehling** [fossasia/yaydoc#12]
The current way of creating a documentation site is as follows:
1. Usually repositories use md files on Github 
2. In a project developers then convert the files to rst files manually or automatically (Readme.md to rst and /docs folder files)
3. In the next step a site in a desired repository or location is generated

In the loklak server project the PR https://github.com/loklak/loklak_server/pull/1142 was merged that converts an md file automatically to an rst file.

Propose and implement a way to make this process part of the automatic generation process.

How can we generate a documentation site from md files and instead of keeping md and rst files in the original repository only host md files as source files?

**Comment by imujjwal96** [comment]
@mariobehling I was thinking that after we merge https://github.com/loklak/loklak_server/pull/1127  we can run that python script in the `.utility/update-docs-repo.sh` to generate .rst file from the .md file and moving that file in the subtree.

**Comment by pri22296** [comment]
@mariobehling We can use recommonmark as used [here](https://github.com/loklak/loklak_server/blob/development/docs/conf.py) in our generated conf.py to handle md files. Only those files which are included in the index.rst(usually README) need to be converted to rst explicitly. for that we can use the mentioned python script.

**Comment by sch00lb0y** [comment]
as @pri22296 suggestion we can can change the config to handle md files also. now i'll make changes script for handling md files also

**Comment by pri22296** [comment]
To know which markdown files are included with an include directive in index.rst, we would need to parse the index.rst supplied by the user and modify it to point to our newly generated rst file. How do we do that? Any ideas? @imujjwal96 @sch00lb0y

**Comment by pri22296** [comment]
Using the idea from [this class](https://github.com/miyakogi/m2r/blob/85d21e2dd53bb65892a60795643c7b03fcbe848e/m2r.py#L472), I have introduced a new directive
mdinclude that can include markdown files. But the automatic conversion of markup documents are not 100% reliable. how do we handle those cases when due to incorrect conversion, html is not rendered properly?
