### ISSUE TITLE
Make WebUI simpler

### ISSUE THREAD

**Issue by mariobehling** [fossasia/yaydoc#120]
Please simplify the WebUI as follows:

Delete
* Author (author is already defined in the github PRs)
* Version (no need, use the date and time)
* Project name and use the name from the repository stated for now
* Doc Path: Always use "/docs" for now

Doc Theme
* Change to dropdown of standard doc themes

**Comment by pri22296** [comment]
@mariobehling We do have sensible defaults for Author, version, project name. It's just that the current layout for the webUI does not consider it. would it be fine if the layout is modified to only ask for essential variables in the primary form and have a checkbox or something like that to let the user modify other non essential variables?

**Comment by pri22296** [comment]
@mariobehling close this?
