### ISSUE TITLE
Remove travis implementation

### ISSUE THREAD

**Issue by pri22296** [fossasia/yaydoc#121]
Since the webUI would be the primary area for users interacting with yaydoc, and we also intend use github signon to auto deploy to ghpages branch, the travis implementation becomes redundant.
Although it should not be removed, till a github hook or integration has been implemented.

**Comment by imujjwal96** [comment]
@mariobehling  @niranjan94  What do you suggest?

**Comment by pri22296** [comment]
@mariobehling @niranjan94 Now since Continuous Integration has been introduced in the webUI, should we proceed with this?

**Comment by niranjan94** [comment]
Yep. I think it can be removed.

**Comment by pri22296** [comment]
Will go ahead with this once CI deploy is in a stable condition
