### ISSUE TITLE
run the sockets in custom namespace

### ISSUE THREAD

**Issue by sch00lb0y** [fossasia/yaydoc#126]
### This is a
- [ ] Feature request
- [x] Bug report

### Current behaviour

socket is running on default namespace. if two user generate documention on same time. There will be a mismatch in the log display or may different download url will be emitted
### Expected behavior

run the sockets in unique custom channel

### Steps to reproduce
1.
2.
3.

**Comment by imujjwal96** [comment]
I am not able to reproduce the error

**Comment by sch00lb0y** [comment]
let say if more than five users execute generate button. they will be ended in joining the same channel. Server socket will start to emit log for the different child process. The  process which ended first will emit success event and then download URL which emitted first will be updated in all the five browsers but this some corner case which may happen

**Comment by imujjwal96** [comment]
Are you sure about that? Because from what I researched, when we use socket.emit() to emit messages, an individual connection is setup for each user communicating with the channel.

**Comment by sch00lb0y** [comment]
i agree with you @imujjwal96 . I just confused with a global variable with the local variable. I'll close this issue then. Thanks for your clarification

**Comment by sch00lb0y** [comment]
@imujjwal96 please check this [example](https://socket.io/get-started/chat/). I'm not understanding. if it this case
> when we use socket.emit() to emit messages, an individual connection is setup for each user communicating with the channel.

how everyone getting the message

**Comment by imujjwal96** [comment]
here, they use io.emit()
there is a difference between io.emit() and socket.emit()

**Comment by imujjwal96** [comment]
I request you to not raise an issue before checking if that issue even exists or not.
It'll waste your and everybody else's time
