### ISSUE TITLE
gh-pages not deployed automatically on each merged PR

### ISSUE THREAD

**Issue by mariobehling** [fossasia/yaydoc#129]
The gh-pages branch should be generated automatically on each merged PR.

**Comment by imujjwal96** [comment]
This is due to the change in the directory structure.
Will look into this.

**Comment by pri22296** [comment]
This should be fixed by #125

**Comment by imujjwal96** [comment]
@pri22296  I was thinking, since cloning yaydoc will also clone  the content from the WebUI, can we split the content required for CI to a different branch using subtrees and clone only that branch?

**Comment by pri22296** [comment]
@imujjwal96 nice idea. that should save us some build time. But let's keep that low priority. It can be done later on when we have basic functionality set up. anyways could you create a issue for the same?

**Comment by pri22296** [comment]
Close this?
