### ISSUE TITLE
Split documentation generation content to a new branch

### ISSUE THREAD

**Issue by imujjwal96** [fossasia/yaydoc#130]
### This is a
- [ ] Bug report
- [x] Feature request

### Current behaviour

In order to generate documentation using CI, the whole yaydoc repository is cloned, including the WebUI content
### Expected behaviour

Clone only the content required to generate documentation

**Comment by pri22296** [comment]
@imujjwal96 This is no longer needed as we are going to remove the travis implementation. close this?
