### ISSUE TITLE
Ask user to input username and repository name instead of URL

### ISSUE THREAD

**Issue by imujjwal96** [fossasia/yaydoc#142]
### This is a
- [ ] Bug report
- [x] Feature request

### Description

The user is asked to input a url of their repository in the webapp. Apparently, there can be different ways of inputting a URL. Asking the user to input username and repository name would be simpler for the user to input. Also, it will be simpler in our end to generate a URL from it.

**Comment by pri22296** [comment]
How about if we use a login with github option with just basic permissions like info. we can then get the user name from that and we could even display a list of all repositories of the user to select from?

**Comment by imujjwal96** [comment]
what if I want to generate a repository of any random repository?

What I plan to do here is,
When a user inputs a username, that username will be verified using the GithubAPI, after it is found that the username exist, we will do the same for his or her repository

**Comment by pri22296** [comment]
Good point about random repositories. I overlooked that. Please proceed with this.

**Comment by mariobehling** [comment]
Please see the relevant comment here, why this is not an improvement: https://github.com/fossasia/yaydoc/pull/144#issuecomment-309502802
