### ISSUE TITLE
Provide new config var DEBUG for extended logging

### ISSUE THREAD

**Issue by pri22296** [fossasia/yaydoc#148]
### This is a
- [ ] Bug report
- [x] Feature request

<strike>Following discussion at PR #143 , upload generated index.rst to pastebin and share the link in the build logs.</strike>
Provide a new config var DEBUG which can be set to true, to get extended logging for debugging purposes. This would also print out all auto-generated configuration files.

**Comment by pri22296** [comment]
considering https://github.com/fossasia/yaydoc/pull/143#issuecomment-309492484, how about if we create an extra variable `DEBUG`, which if true would log certain things such as the autogenerated index.rst? @imujjwal96 your views?

**Comment by imujjwal96** [comment]
where will we use it in the WebUI? A checkbox?

**Comment by pri22296** [comment]
Currently most of the configuration variables are not available from the webUI for simplicity. Although if added, a checkbox seems fine for such a purpose. Anyways for now, it would available by either an environment variable or specifying in the `.yaydoc.yml` file.
