### ISSUE TITLE
add repository search feature in WebUI

### ISSUE THREAD

**Issue by sch00lb0y** [fossasia/yaydoc#149]
### This is a
- [ ] Bug report
- [x] Feature request

### Current behaviour

user has to enter the whole url in the input box
### Expected behavior

add auto fill feature to the input box so that it show list of  user's repository and the user can select from the list.

### Steps to reproduce
1.
2.
3.

**Comment by pri22296** [comment]
@sch00lb0y When PR #144 gets merged, you might have to update the description of the PR

**Comment by pri22296** [comment]
Since #144 was closed, this no longer makes sense. close this? @sch00lb0y @imujjwal96
