### ISSUE TITLE
Add ability to build using custom themes

### ISSUE THREAD

**Issue by pri22296** [fossasia/yaydoc#15]
PR #13 added a configuration variable to specify a built in theme. But currently there is no way for a user to specify a custom theme from pypi.

**Comment by pri22296** [comment]
I'd like to work on this

**Comment by sch00lb0y** [comment]
since we working on our own theme i don't think we need this customization

**Comment by mariobehling** [comment]
We might use different themes for different projects. So, if this helps with it, then we need it.
