### ISSUE TITLE
Add integration test for documentation generation

### ISSUE THREAD

**Issue by sch00lb0y** [fossasia/yaydoc#154]
### This is a
- [ ] Bug report
- [x] Feature request

### Expected behaviour

Add unit test for documentation generation. it should contain following test case.
- generate script should return exit code 0
- documentation zip file has to be created in the temp folder
- preview folder has to be created in temp folder

### Steps to reproduce
1.
2.
3.

**Comment by pri22296** [comment]
@sch00lb0y @imujjwal96 Is the document preview and zip file meant to be permanently stored? wouldn't that fill up the space very quickly?

**Comment by imujjwal96** [comment]
No, we'll keep the preview few hours and zip for few days. I am working on that in the Mail zip issue

**Comment by imujjwal96** [comment]
@sch00lb0y you must know that the tests you describe here are not unit tests. Rather, they are integration tests
