### ISSUE TITLE
Error on deploying to ghpages from yaydoc.herokuapp.com

### ISSUE THREAD

**Issue by pri22296** [fossasia/yaydoc#157]
### This is a
- [x] Bug report
- [ ] Feature request

### Current behaviour

While deploying docs for https://github.com/pri22296/testYaydoc2 from yaydoc.herokuapp.com, I get the following error message:

![screenshot 151](https://user-images.githubusercontent.com/11555869/27298483-6e121d74-5546-11e7-8dc5-5b27565725e0.png)

### Expected behaviour

The docs should have been successfully pushed to ghpages

**Comment by pri22296** [comment]
@sch00lb0y @imujjwal96 Please look into this

**Comment by imujjwal96** [comment]
This is because of the absence of an environment variable in Heroku which somehow schoolboy forgot to mention.
I'll add that in Heroku now.

**Comment by imujjwal96** [comment]
If you may, `ENCRYPTION_KEY` is the environment variable

**Comment by imujjwal96** [comment]
I've added it. Can you please check again?

**Comment by pri22296** [comment]
Yeah that error has been fixed. But there seems to be a new issue again.
preview-url: http://yaydoc.herokuapp.com/preview/priyamsingh.22296@gmail.com/c2ee829b-b0f9-4e81-9ce8-a2b2bc7c5042_preview/
ghpages url: https://pri22296.github.io/testYaydoc2/

ghpages isn't rendered properly

**Comment by imujjwal96** [comment]
i dont see any difference
