### ISSUE TITLE
Register repositories from WebUI for continuous deployment 

### ISSUE THREAD

**Issue by imujjwal96** [fossasia/yaydoc#158]
### This is a
- [ ] Bug report
- [x] Feature request

### Current behaviour

The documentation is deployed to gh-pages, but after that deployment, there is no redeployment at each commit/change in the docs.
### Expected behaviour

Docs should be redeployed after each change in them

**Comment by imujjwal96** [comment]
I can think of two ways of solving this. Since we are not inclined towards creating our own integration yet, we can ask the user to update their travis configuration. Or, we can ourselves parse their `.travis.yml` (if it exists) and add the necessary configuration for our app.

@pri22296 @sch00lb0y  opionions?

**Comment by pri22296** [comment]
How about if we create a github hook and use it to build and publish on each commit? would that work?

**Comment by imujjwal96** [comment]
Can you please elaborate? How it will work?

**Comment by pri22296** [comment]
AFAIK, a github hook would recieve json similar to https://gist.github.com/gjtorikian/5171861 on each push event. we can extract the url of the HEAD and build and push to ghpage from it. Never worked with github hooks before so can't say anything about details.

**Comment by imujjwal96** [comment]
i haven't either. Does this require any work from our server?

**Comment by pri22296** [comment]
Sorry, I didn't consider that. If that's the case, webhooks may be a no-no. specifying instrcutions for travis.yml seems to be the only option then. could you elaborate the second idea?

**Comment by imujjwal96** [comment]
we can add to the travis.yml of the main branch of their repository, the configurations required to deploy documentations.

**Comment by pri22296** [comment]
Ok that's a good idea. but we might need to be careful though with directly modifying travis.yml. It would be best if we could display the new travis.yml before pushing and only if the user agrees, then push the changes.

**Comment by imujjwal96** [comment]
Should we make an editable display? The user will be able to edit the file at the time of its preview.

**Comment by pri22296** [comment]
good idea

**Comment by imujjwal96** [comment]
Can you start the work with writing the script. 
I'll update the WebUI

**Comment by pri22296** [comment]
Just to be clear, we'll need to add [this](https://github.com/fossasia/yaydoc#travis-configuration) right?

**Comment by imujjwal96** [comment]
No, this is deprecated now. Please look at this repository's `.travis.yml`, as we will deploy the docs only when the previous tests have passed.

**Comment by imujjwal96** [comment]
@pri22296 What about the environment variables?

**Comment by pri22296** [comment]
I'm not sure if we can run multiple commands in the script deployment with travis. https://docs.travis-ci.com/user/deployment/script/
If we expose environment variables in the webUI, we might add them to travis.yml. I don't know how OAUTH_TOKEN would be handled though here. users would still need to set it up manually or use ssh. I don't think we can automate that.

**Comment by imujjwal96** [comment]
We do receive a token for the WebUI to publish the docs. Can we use that here?

**Comment by pri22296** [comment]
we'll need to encrypt that. so we would also need user's travis's login information! It can be done. but it would be much work both in the UI end and in the script. Maybe postpone this for the future. For the time being we could use your first idea of just displaying what to add in travis.yml. Anyways, It would be a one time addition so shouldn't matter much to the user.

**Comment by imujjwal96** [comment]
I dont think so
