### ISSUE TITLE
Handle Multiple Repositories with Yaydoc

### ISSUE THREAD

**Issue by imujjwal96** [fossasia/yaydoc#160]
### This is a
- [x] Feature request
- [ ] Bug report

## Description
Currently, yaydoc can only generate and deploy documentation of a project hosted in a single repository.
Since there are multiple open source projects that are not limited to only a single repository, and have multiple subprojects that are dependent on a master project, we need yaydoc to be competent Enugu to generate a single static website for their documentation.

References:
https://github.com/fossasia/yaydoc/pull/144#issuecomment-309502802

**Comment by imujjwal96** [comment]
@pri22296  @sch00lb0y  Ideas?

**Comment by sch00lb0y** [comment]
I was doing research on this. we can clone all the repository doc and we'll create an index documentation page in which create a relation to all the documentation.

**Comment by pri22296** [comment]
I think we need functionality similar to http://docs.readthedocs.io/en/latest/subprojects.html. To achieve this, we may take a list of subprojects and their docpath's as input. we would copy the respective subproject's docpath as a subfolder of the master project's docpath. we'll also need to generate a proper index.rst(this might be left for now. for now let's expect users to fill the index.rst appropriately).

**Comment by imujjwal96** [comment]
A new repository for documentation or the master repository with docs deployed in `gh-pages`?

**Comment by imujjwal96** [comment]
What would be the flow now?
Should we first create a script and work with Travis implementation, like we did with Single Repository? Or should we keep both UI and backend in sync?

**Comment by pri22296** [comment]
I vote for the the first approach. 

> A new repository for documentation or the master repository with docs deployed in gh-pages

could you elaborate?

**Comment by imujjwal96** [comment]
Where should the documentation generated be published? :)

**Comment by pri22296** [comment]
The user would have to create a new repository to act as a holder project(like dev.loklak.org) and use yaydoc on the master project. Now building the holder project, would also clone all it's sub-projects and the generated documentation would be published to the ghpages branch of the holder project.

**Comment by imujjwal96** [comment]
Ok! So that means, the travis configuration will exist in the holder project. It will have the information about the repositories that will be cloned.

**Comment by imujjwal96** [comment]
What if a project doesn't have any master repository?

**Comment by pri22296** [comment]
User would need to create one. I can't think of any other way.

**Comment by imujjwal96** [comment]
if the user doesn't have a master repository, then the documentation repository will have the markdown for the start page. 
Makes sense?

**Comment by pri22296** [comment]
Nopes. 

> markdown for the start page.

care to explain this part?

**Comment by imujjwal96** [comment]
Check this https://github.com/loklak/dev.loklak.org/issues/2

**Comment by pri22296** [comment]
cool. Let's say i have 3 projects

- projectA
- projectA-sub1
- projectB-sub2

I would setup yaydoc in projectA and set projectA-sub1 and sub2 as the sub projects. In this case there would no need to create a holder project.

But if the three projects are totally unrelated, but i want them under a single domain, in that case a seperate holder project would be required. Makes sense?

**Comment by imujjwal96** [comment]
Yes!

**Comment by sch00lb0y** [comment]
can we have this as two issues like web UI implementation and Travis implementation? so that we'll split the work and can work together. @imujjwal96 @pri22296

**Comment by imujjwal96** [comment]
As decided, we will first work on the Travis implementation. There is no need to create a separate issue yet.

**Comment by imujjwal96** [comment]
Let's start with the project that requires creation of a Holder repository. I have this organisation https://github.com/BrimeNotes We can use it for the development.

**Comment by imujjwal96** [comment]
https://github.com/fossasia/yaydoc/issues/160#issuecomment-309719680
@pri22296 did you check if intersphinx support search functionality?

**Comment by pri22296** [comment]
I read about it and it seems search wouldn't work with it. but I didn't test it. I'll test it today.

**Comment by imujjwal96** [comment]
How should we start now?
I will create a new repository in https://github.com/BrimeNotes with the name `docs`.

@pri22296   we should add the information about the sub-projects and their hierarchy in the `yaydoc.yaml` file?

**Comment by pri22296** [comment]
Yep. Also the config.py file would need to be modified accordingly. I'll submit a PR for that by today. what should be the environment variable's format??
SUBPROJECTS = url1,url2 ?? or something else?

**Comment by sch00lb0y** [comment]
Since you both working on Travis implementation so, I'll work on WEBUI implementation. it'll boosts the development speed as well.

**Comment by pri22296** [comment]
As this is a big issue, I agree with https://github.com/fossasia/yaydoc/issues/160#issuecomment-309970408 . Let's create seperate issues. Let's keep this issue as a parent issue for tracking overall development. This would help us avoid situations like https://github.com/fossasia/yaydoc/pull/169#discussion_r123690699
@imujjwal96 @sch00lb0y Your views?

**Comment by imujjwal96** [comment]
Situations like that wouldn't have raised if Scrums of peers will be checked.
Anyway, i'm fine with separate issues.
