### ISSUE TITLE
Update test cases for generate script in test.js 

### ISSUE THREAD

**Issue by imujjwal96** [fossasia/yaydoc#163]
### This is a
- [x] Bug report
- [ ] Feature request

### Description
Testing a function shouldn't be limited to testing it only with a case that always pass. We should also include those cases in which it is expected to fail. 
For the generate script, these may include those cases in which exit codes other than code 0 is returned.

**Comment by imujjwal96** [comment]
After doing some research, it turns out that the reason for the failure of the generate script would be internal to the modules being called in the script. Hence, it would not be possible to write proper test for them.

@pri22296  @sch00lb0y  Opinions?

**Comment by pri22296** [comment]
would mocking `zip`, `sphinx-quickstart` and `make` work?

**Comment by imujjwal96** [comment]
How can we do that?

**Comment by pri22296** [comment]
maybe something from https://stackoverflow.com/questions/25399079/how-to-overwrite-a-bash-command
