### ISSUE TITLE
Integrate travis for build tests

### ISSUE THREAD

**Issue by mariobehling** [fossasia/yaydoc#17]
Add travis to the repo.

**Comment by imujjwal96** [comment]
Do we need Travis for unit testing of generate.sh file?

**Comment by mariobehling** [comment]
This repo will be expanded step by step. One goal is to have a simple tool to be able to build documentation by entering the repository in a web form and to get the final documentation deployed via ftp or on github pages (similar to Open Event Web App). So, in this regard it makes sense to get this repository ready for tests.
![screenshot from 2017-05-14 13-54-37](https://cloud.githubusercontent.com/assets/1583873/26033462/2a662e9a-38ad-11e7-82a2-4490493d8544.png)

**Comment by imujjwal96** [comment]
So for now, we'll just have to add a sample, no-fail travis configuration which will be extended as the project updates. Is it correct?

**Comment by mariobehling** [comment]
yes

**Comment by imujjwal96** [comment]
Thanks a lot for the clarification.
