### ISSUE TITLE
Exported variables from generate.sh may affect concurrent builds

### ISSUE THREAD

**Issue by pri22296** [fossasia/yaydoc#170]
### This is a
- [x] Bug report
- [ ] Feature request

### Current behaviour

See [this](https://github.com/fossasia/yaydoc/pull/162#discussion_r123515912) thread for details.
Need to investigate if this is actually a issue and if it is, instead of exporting, pass variables as parameters to `config.py`.

### Steps to reproduce
1.
2.
3.

**Comment by sch00lb0y** [comment]
@pri22296 you working on this?

**Comment by pri22296** [comment]
No, Did you find out some problems during concurrent builds?

**Comment by sch00lb0y** [comment]
@pri22296 Nope, but I think this is a serious issue to be taken care. because we going to integrate yaydoc to all fossasia project. we'll get more CI request yaydoc have a good chance of facing this problem. I'll investigate and I'll update the status here.

**Comment by pri22296** [comment]
@sch00lb0y I agree. Please proceed with this.

**Comment by sch00lb0y** [comment]
I think this won't affect the concurrent build. export variable will be accessed by the child process created by that script. please check this thread https://stackoverflow.com/questions/1158091/defining-a-variable-with-or-without-export.

**Comment by pri22296** [comment]
Oh cool. should we close this then?
