### ISSUE TITLE
Build Error on choosing theme as editorial_sphinx_theme

### ISSUE THREAD

**Issue by pri22296** [fossasia/yaydoc#179]
### This is a
- [x] Bug report
- [ ] Feature request

### Current behaviour

![screenshot 163](https://user-images.githubusercontent.com/11555869/27506733-f2846384-58dc-11e7-9f86-992906c1d9bc.png)

### Steps to reproduce
1. go to yaydoc.herokuapp.com
2. fill the form and choose editorial_sphinx_theme

**Comment by pri22296** [comment]
@imujjwal96 how do we see `Register for continuous development` here? yaydoc.herokuapp.com is supposed to be deployed from this repo's master branch right?

**Comment by imujjwal96** [comment]
there was some error in a recent build. I'll have a look into it

**Comment by pri22296** [comment]
Turns out the problem is with the package itself. Even locally installing it with `pip install editorial_sphinx_theme` and then trying to import it fails. It seems that the theme wasn't packaged properly. Therefore I think we should just remove this theme from our list and replace it with some other maybe. @imujjwal96 @sch00lb0y views?
