### ISSUE TITLE
The use of ENCRYPTION_KEY and SECRET

### ISSUE THREAD

**Issue by imujjwal96** [fossasia/yaydoc#181]
AFAIK, the ENCRYPTION_KEY is used in encrypting values using crypter.js whereas SECRET is used as a token for Session Secret.

The question is, can't we use just one key for both these functionalities?

**Comment by pri22296** [comment]
@sch00lb0y views?

**Comment by sch00lb0y** [comment]
it is better to have a different key. because `ENCRYPTION_KEY` is so sensitive because we encrypting GitHub OAuth token and we templating publically in the frontend. if secret get leaked at least `ENCRYPTION_KEY` will be safe. if we add any further secret key we'll reuse the same
