### ISSUE TITLE
send a  themed HTML email 

### ISSUE THREAD

**Issue by sch00lb0y** [fossasia/yaydoc#186]
### This is a
- [ ] Bug report
- [x] Feature request

### Current behaviour

Now we sending normal HTML email after documentation generation
### Expected behaviour

Instead of sending normal HTML email. send themed HTML email after documentation generation, 

### Steps to reproduce
1.
2.
3.

**Comment by yukiisbored** [comment]
Why do we need this? Some people (including myself) doesn't use graphical mail clients thus making HTML on mail look unreadable and garbage.

**Comment by sch00lb0y** [comment]
@yukiisbored we are sending both HTML and plain text 
```
  client.sendMail({
    from: 'info@yaydoc.com',
    to: data.email,
    subject: 'Preview your generated docs - Yaydoc',
    text: textContent,
    html: htmlContent
  }, function (error, info) {
```
email is generated using [mjml](http://mjml.io/). so email will be responsive across device.
