### ISSUE TITLE
add support to create toc tree for multiple repository

### ISSUE THREAD

**Issue by sch00lb0y** [fossasia/yaydoc#188]
### This is a
- [ ] Bug report
- [x] Feature request

### Current behavior

Now `genindex.py` create toc tree for an only single repository.
### Expected behavior

make a parser to create toc tree to support multiple repositories.
### Steps to reproduce
1.
2.
3.

**Comment by imujjwal96** [comment]
@sch00lb0y What's the update on this?

**Comment by pri22296** [comment]
@imujjwal96 This issue was already fixed at #199 . Please close this.
