### ISSUE TITLE
WebUI logs do not handle newline within message

### ISSUE THREAD

**Issue by pri22296** [fossasia/yaydoc#205]
### This is a
- [x] Bug report
- [ ] Feature request

### Current behaviour

If a message contains newline chanracters, It is still printed as a single line.

### Expected behaviour

If a message recieved from the script contains newline character, It should be splitted into multiple lines.

**Comment by imujjwal96** [comment]
@pri22296 Are you working on it? I have its solution and can send a PR right away

**Comment by pri22296** [comment]
Haven't started yet. feel free to submit a PR
