### ISSUE TITLE
Add support to use existing herokuapp for deploying

### ISSUE THREAD

**Issue by sch00lb0y** [fossasia/yaydoc#209]
### This is a
- [ ] Bug report
- [x] Feature request

### Current behavior

New app is created for each on every deploy
### Expected behavior

add a feature to use existing app to deploy documentation
### Steps to reproduce
1.
2.
3.

**Comment by imujjwal96** [comment]
i have already made the changes in https://github.com/fossasia/yaydoc/pull/207

**Comment by imujjwal96** [comment]
Fixed via: https://github.com/fossasia/yaydoc/pull/207
