### ISSUE TITLE
Add support for continuous deployment from yaydoc

### ISSUE THREAD

**Issue by sch00lb0y** [fossasia/yaydoc#210]
### This is a
- [ ] Bug report
- [x] Feature request

### Current behavior

right now we have been using Travis to push documentation 
### Expected behavior

use yaydoc instead of using Travis to push documentation 

### Steps to reproduce
1.
2.
3.

**Comment by sch00lb0y** [comment]
I did some research on this.
we'll have button saying that continuous deployment. if user click we'll register webhook, save the encrypted access_token in the db. if webhook triggers we'll push the generated documentation using saved access_token. 
@imujjwal96 @pri22296 would love to hear your feedback on this workflow?

**Comment by imujjwal96** [comment]
We did discuss this. It is not possible to register webhook for a website hosted on Heroku

**Comment by sch00lb0y** [comment]
@imujjwal96 are you sure about this. because I have seen a project which using github webhook on heroku.
https://github.com/jgierer12/prettier-github
please check

**Comment by pri22296** [comment]
It's possible but I think we discussed that with a free account this was not feasible.

**Comment by sch00lb0y** [comment]
if GitHub sends webhook to Heroku then we can also push the documentation because we already pushing the documentation via Heroku. so can proceed with the above discussed flow?

**Comment by pri22296** [comment]
Yeah I understand, but let's assume when a large number say 100 projects are registered. We may recieve a large number of hooks from github simultaneously. Are you sure that with a free heroku account building 100's of projects simultaneously would be feasible?

**Comment by sch00lb0y** [comment]
If that is the scenario even our web UI can't handle the situation by building 100 projects. Right now we using free tier Heroku to show the progress. If yaydoc gets more users anyways we have to scale by adding resources.it is not that we will be hosting only in free tier.

**Comment by imujjwal96** [comment]
> it is not that we will be hosting only in free tier.

I think that this is something that needs to be discussed with the mentors.
