### ISSUE TITLE
Progress bar finishes before website link button is displayed in heroku deploy

### ISSUE THREAD

**Issue by pri22296** [fossasia/yaydoc#214]
### This is a
- [x] Bug report
- [ ] Feature request

### Current behaviour

![screenshot 169](https://user-images.githubusercontent.com/11555869/27764185-b93fa186-5eb0-11e7-9a2f-15b28047530f.png)

### Steps to reproduce
1.
2.
3.

**Comment by imujjwal96** [comment]
@pri22296 are you working on this? If you wouldn't mind, i'd like to solve this issue

**Comment by pri22296** [comment]
sure
