### ISSUE TITLE
Error if SUBPROJECT_URLS is defined but SUBPROJECT_DOCPATHS is not

### ISSUE THREAD

**Issue by pri22296** [fossasia/yaydoc#227]
### This is a
- [x] Bug report
- [ ] Feature request

### Description

Currently If `SUBPROJECT_URLS` is set but `SUBPROJECT_DOCPATHS` is not, there is a error because the script assumes that both will always be set and have the same number of token seperated by comma,
This happens because of the how config.py operates. There is no way for this to be fixed without creating special cases with the current implementation which should be avoided.

https://github.com/fossasia/yaydoc/pull/224#discussion_r126084331

**Comment by imujjwal96** [comment]
Here too @pri22296  :)

**Comment by pri22296** [comment]
@imujjwal96 @sch00lb0y I need your suggestion here. Providing the ability to set variables via environment variables apart from .yaydoc.yml is posing a difficulty here. config.py will only come into play when .yaydoc.yml has a corresponding entry. If there is no entry, environment variables are never changed as per design. So when env vars are directly defined for SUBPROJECT_URLS but not for SUBPROJECT_DOCPATHS, this leads to error because both of them are related variables.
Here are the possible fixes I could think of:

- Document that both of them need to be set up when setting via env vars
- Have a single variable instead of two vars(seems a short term solution, may again lead to similar situation when env  vars depend on each other)
- Remove the option of configuration via env vars.

what do you suggest?

**Comment by imujjwal96** [comment]
Can you elaborate the third option?

**Comment by pri22296** [comment]
By the third option I meant, `yaydoc.yml` should be enough for users to specify configuration options. Why do we also need to support setting configuration values such as themes via environment variables?

**Comment by imujjwal96** [comment]
How and where are these environment variables set?

**Comment by pri22296** [comment]
Currently for every entry in the `.yaydoc.yml`, there is a corresponding environment variable which the user can set to achieve the same result. `.yaydoc.yml` will never override environment variables if set.

Let's say, To set a theme, user can specify this in `yaydoc.yml`

```yaml
metadata:
  doctheme: sphinx_fossasia_theme
```
or,

set DOCTHEME=sphinx_fossasia_theme as an environment variable

**Comment by imujjwal96** [comment]
in the travis configuration?

**Comment by pri22296** [comment]
Yep

**Comment by imujjwal96** [comment]
With the Webhook being introduced in the WebUI, do we really need the travis configuration?

**Comment by pri22296** [comment]
It does help with quick testing sometimes. but overall I don't think so. There is a corresponding issue for it as well at https://github.com/fossasia/yaydoc/issues/121

**Comment by imujjwal96** [comment]
Talk to mentors about it then?

**Comment by pri22296** [comment]
closing this as it's no longer relevant.
