### ISSUE TITLE
Add test case for deploy scripts in WEBUI

### ISSUE THREAD

**Issue by sch00lb0y** [fossasia/yaydoc#233]
### This is a
- [ ] Bug report
- [x] Feature request

### Current behaviour

In `test.js` test is running only for generate script
### Expected behavior

The current test also testing the script not the js function so refactor the existing test case to test the js function and also include test for deploy.js

### Steps to reproduce
1.
2.
3.

**Comment by imujjwal96** [comment]
Close this!
