### ISSUE TITLE
Bug Report

### ISSUE THREAD

**Issue by imujjwal96** [fossasia/yaydoc#236]
### This is a
- [x] Bug report
- [ ] Feature request

@pri22296  Can you please have a look at this. I guess it is due to one of your PRs
![image](https://user-images.githubusercontent.com/8245662/27991875-570dd314-64a2-11e7-8ca7-618644d64f73.png)

**Comment by imujjwal96** [comment]
@pri22296 Also you didn't add `p:` here

![image](https://user-images.githubusercontent.com/8245662/27991881-84b0842e-64a2-11e7-86cb-2dbb580bb528.png)

**Comment by pri22296** [comment]
@imujjwal96 This happens when there are no subprojects added. Never tested the Subproject PR without subprojects. My bad. PR #230 fixes the first issue. I'll make changes for the second one in that PR.
