### ISSUE TITLE
Add support to choose theme in CI

### ISSUE THREAD

**Issue by sch00lb0y** [fossasia/yaydoc#238]
### This is a
- [ ] Bug report
- [x] Feature request

### Current behaviour

Now default alabaster theme is used for documentation in CI
### Expected behavior

allow user to choose their custom theme on their own

### Steps to reproduce
1.
2.
3.

**Comment by imujjwal96** [comment]
I guess we should let this be handled by `.yaydoc.yml` 
Just like travis requires it's users to have a configuration file for it to work we should have that here as well.
@pri22296 what do you think?

**Comment by pri22296** [comment]
@imujjwal96 I agree. In the webUI, we should only ask for variables which are absolutely necessary for the build. This would help us keep the webUI clean.

**Comment by imujjwal96** [comment]
What are these variables? Can't they be added in the configuration file?

**Comment by pri22296** [comment]
The only variable is GITURL. It doesn't makes sense to make this part of the yaml file as this is only used by the webUI. The idea is that user should be able to generate a minimal documentation without .yaydoc.yml. However for any customization, they would need to create the file.

**Comment by imujjwal96** [comment]
In the wake of promoting the use of .yaydoc.yml, we can keep a default theme if the file doesn't exist

**Comment by pri22296** [comment]
Yeah, that's already implemented. The default theme is fossasia_theme currently.

**Comment by pri22296** [comment]
@sch00lb0y close this?

**Comment by imujjwal96** [comment]
Closing this!
