### ISSUE TITLE
Links to subprojects aren't added in sidebar by the autogenerated index.rst

### ISSUE THREAD

**Issue by pri22296** [fossasia/yaydoc#239]
### This is a
- [x] Bug report
- [ ] Feature request

### Current behaviour

Currently It seems the toctrees for subprojects are added in the globaltoc which doesn't render on themes like alabaster by default.

### Expected behaviour

The default behaviour should be that the sidebar should always contain links to subprojects

**Comment by pri22296** [comment]
@imujjwal96 I tried this, but i could not find a reliable way to do this without conflicting with some of the other themes. In fact, this problem seems like a issue, which should be done at the theme level. Different themes display contents in the sidebar differently. For example, AFAIK, sphinx_rtd_theme renders both the localtoc and the globltoc in the sidebar, alabaster provides a navigation.html for this purpose. IMO we should leave this to the user to choose a specific theme which displays the sidebar according to their own preferences.

**Comment by imujjwal96** [comment]
@pri22296 I suppose we had a PR that solved this

**Comment by pri22296** [comment]
Yep. Fixed by #365
