### ISSUE TITLE
Provide option to specify branch and docpath in the webUI

### ISSUE THREAD

**Issue by pri22296** [fossasia/yaydoc#251]
### This is a
- [ ] Bug report
- [x] Feature request

### Parent Issue
#250 

### Current behaviour

Currently if a user wants to use another value for DOCPATH instead of the default `docs/`, they would need to create a `.yaydoc.yml` file in their repo.

### Expected behaviour

Quoting @imujjwal96 from official gitter channel of Yaydoc

> From the perspective of the WebUI, i think we can add two additional (ADVANCE SETTINGS) inputs which are hidden by default. These two can be the branch name and docpath
with the default value as Default branch and docs/ respectively

**Comment by imujjwal96** [comment]
Since #256 is merged, started working on this.

**Comment by imujjwal96** [comment]
@pri22296 what will happen when the specified docpath isn't a valid directory?

**Comment by pri22296** [comment]
https://github.com/fossasia/yaydoc/blob/1ec16711afc1b262716a4383e818f82fb336a9d7/generate.sh#L99 Here is the first time we switch to DOCPATH. what should be the behaviour of `cd` in this case?

Overall, `undefined behaviour`, probably would result in a build error

**Comment by imujjwal96** [comment]
How should i handle this?
Check if the directory exist or not. If it doesn't exist. Stop and display error?

**Comment by pri22296** [comment]
Yep, There is no reason to proceed with the build if DOCPATH is invalid.
Anyways is this related to this issue?

**Comment by imujjwal96** [comment]
Since we are letting the user input docpath from the input form, we'll have to be extra careful. We can never expect what the user may input in a form :)

**Comment by pri22296** [comment]
Cool. Just a headsup, when DOCPATH would be set from the webUI, `.yaydoc.yml` will be overridden.

**Comment by imujjwal96** [comment]
That is good! The user may test configurations from the WebUI and then set the values in their `.yaydoc.yml` for Continuous integration

**Comment by imujjwal96** [comment]
@pri22296 Wasn't there a default value for DOCPATH

**Comment by pri22296** [comment]
Yep there is. `docs`

**Comment by imujjwal96** [comment]
@pri22296 i think the opposite is happening 

```
# Setting environment variables
ENVVARS="$(python ${BASE}/modules/scripts/config.py "${USERNAME}" "${REPONAME}")"
echo -e "\n${ENVVARS}\n" >> ${LOGFILE}
eval $ENVVARS

echo ${DOCPATH}
if [ ! -d ${ROOT_DIR}/${DOCPATH} ]; then
  print_danger "The specified DOCPATH does not exist.\n"
  exit 5
fi
```

When i perform this, the output os `docs`

**Comment by pri22296** [comment]
Can you share the detailed logs?

**Comment by imujjwal96** [comment]
```
Cloning Repository...

Repository Cloned Successfully!

Installing virtualenv

Installation successful

Creating an isolated Python environment

Python environment created successfully!

Installing packages required for documentation generation

Installation successful


export MOCK_MODULES=""
export MARKDOWN_FLAVOUR="markdown_github"
export AUTHOR="imujjwal96"
export AUTOAPI_PYTHON_PATH="."
export PROJECTNAME="prelimquiz"
export DOCPATH="docs"
export SUBPROJECT_URLS=""
export VERSION="Jul 13, 2017"
export AUTOAPI_JAVA="false"
export SUBPROJECT_DOCPATHS=""
export LOGO=""
export AUTOAPI_JAVA_PATH="."
export AUTOAPI_PYTHON="false"


```

**Comment by pri22296** [comment]
Which repo are you using? Can you share a link?

**Comment by imujjwal96** [comment]
https://github.com/imujjwal96/prelimQuiz

**Comment by pri22296** [comment]
If you are passing the variable from the webUI, you need to `export` it otherwise config.py cannot see your variable

**Comment by imujjwal96** [comment]
okie!
