### ISSUE TITLE
CI Deploy not working

### ISSUE THREAD

**Issue by imujjwal96** [fossasia/yaydoc#252]
### This is a
- [x] Bug report
- [ ] Feature request

### Description

The CI deployment is not working. I registered my repository in the Yaydoc WebUI. Making random commits in my repository has no effect and the documentation is not being generated.

Repository: https://github.com/imujjwal96/mydoc.git

**Comment by pri22296** [comment]
I'm not sure if this helps but,
Registering with the current deployment at yaydoc.herokuapp.com, in the webhook, payload URL is `undefined/ci/webhook`

**Comment by imujjwal96** [comment]
It was an issue in our own deployment. 
The reason was an undefined hostname value, which was fixed by setting the config var in the Heroku deployment.

Thanks @pri22296  and @sch00lb0y 
Closing this!
