### ISSUE TITLE
Multiple commits on documentation generation using CI

### ISSUE THREAD

**Issue by imujjwal96** [fossasia/yaydoc#253]
### This is a
- [x] Bug report
- [ ] Feature request

### Screenshot
![image](https://user-images.githubusercontent.com/8245662/28084891-b9ad258c-6697-11e7-96ab-b67791db4442.png)

![image](https://user-images.githubusercontent.com/8245662/28085279-d64587ec-6698-11e7-991e-3bd65732bbf0.png)
There have been 122 commits and it keeps increasing.

**Comment by sch00lb0y** [comment]
@imujjwal96 are you working on this?

**Comment by imujjwal96** [comment]
No I'm not
