### ISSUE TITLE
Integrating Swagger UI with yaydoc

### ISSUE THREAD

**Issue by imujjwal96** [fossasia/yaydoc#259]
### This is a
- [ ] Bug report
- [x] Feature request

### Description

I did some research and also discussed with the team of susi_server. It was found that the only thing that need to exist in the gh-pages branch for Swagger to work is the Swagger-ui distribution with a change of API url in the index.html file.

The susi_server project already has the api URL set up at http://api.susi.ai/docs/swagger.json. We'll just have to integrate it.

**Comment by imujjwal96** [comment]
Right now, I am researching about automating the build process of the UI

**Comment by pri22296** [comment]
What do you mean by integrate? How does it work exactly? Can you please elaborate?

**Comment by imujjwal96** [comment]
Swagger generates the API of a website. It also provide the [Swagger-UI](https://swagger.io/swagger-ui/) that generates a website using that API. From what i can understand, the only job at our end is to get the  static website (https://swagger.io/docs/swagger-tools/#usage-34), change the url at https://github.com/swagger-api/swagger-ui/blob/master/dist/index.html#L77 and move the directory to gh-pages branch

**Comment by imujjwal96** [comment]
The developer can specify that they are using Swagger in the `.yaydoc.yml` file along with the url of the API

```
additional:
  - swagger:
      url: http://api.susi.ai/docs/swagger.json
```

and reading this info, we can generate integrate Swagger UI

**Comment by imujjwal96** [comment]
@pri22296 Do I make myself clear?

**Comment by pri22296** [comment]
@imujjwal96 It seems we only need to copy the contents of `dist` directory to ghpages. can you confirm?

**Comment by imujjwal96** [comment]
Read the descripion >.<

**Comment by pri22296** [comment]
Oh, I thought by distribution you meant the entire repo of swagger-ui. So silly of me.

> Right now, I am researching about automating the build process of the UI

Can't we just clone the repo and modify the url using regex and then copy it all to ghpages?

**Comment by imujjwal96** [comment]
instead of modifying, will it be possible to set a url variable that will take the value from yaydoc.yml

**Comment by pri22296** [comment]
> instead of modifying, will it be possible to set a url variable that will take the value from yaydoc.yml

I don't understand. We will modify the url used in the index with the url defined in the yaydoc.yml file. How do we avoid modification?

**Comment by imujjwal96** [comment]
![image](https://user-images.githubusercontent.com/8245662/28171007-c09475f8-6804-11e7-9205-b5fcf553afe1.png)
use a variable like `link` and set its value

**Comment by pri22296** [comment]
Yeah, that I understand. We don't have access to the repo. For that we would have to keep a copy of swagger-ui somewhere else where we can make those changes.

**Comment by imujjwal96** [comment]
What are the options? 
- [ ] Host it in a subdirectory in yaydoc 
- [ ] Create a new repo containing only the dist directory. 
- [ ] Fork Swagger UI repo and make changes

**Comment by sch00lb0y** [comment]
check whether this helps or not. there is a sphinx extension https://github.com/unaguil/sphinx-swaggerdoc. we'll improve the toc tree to add JSON file to the index.rst.

**Comment by pri22296** [comment]
@sch00lb0y I tried that extension. There are two problems with it.
- No way to integrate Swagger UI
- There are some major bugs in it currently.

**Comment by pri22296** [comment]
@imujjwal96 I support the first option. The required changes don't seem too big to have a separate repository for it. What do you prefer?

**Comment by imujjwal96** [comment]
There are approximately 30k lines of code to be added

**Comment by pri22296** [comment]
> There are approximately 30k lines of code to be added

Wouldn't it be a mere copy paste?

**Comment by imujjwal96** [comment]
Ignore that comment :)

**Comment by pri22296** [comment]
@imujjwal96 sorry didn't see the updated comment. Shouldn't be too difficult. However, using a regex based solution would have the downside that it may break if there are some major changes in the upstream.

**Comment by sch00lb0y** [comment]
may be we can use some templating like ejs or any python based templating. to replace the html.

**Comment by imujjwal96** [comment]
We are not planning to host our version of the swagger UI. So I don't think `templating` would work.

@pri22296 There are downsides to every approach. Which one do you think has the least?

**Comment by pri22296** [comment]
@imujjwal96 I think the best approach would using the regex based approach, but we clone a specific commit and not the latest, so that we can update it any time but the code won't break automatically. Let's go with the regex based approach.

**Comment by imujjwal96** [comment]
```
apidocs:
  name: swagger
  url: https://api.susi.ai/docs/swagger.json
  ui: swagger
```
Is this fine for yaydoc.yml. Wll you need something similar in API Blueprint

**Comment by pri22296** [comment]
API Blueprint actually needs no configuration for now. For now anything is ok for `.yaydoc.yml` as while adding options I didn't really thought about it's design a lot. We may have to review the design of `.yaydoc.yml`later on.
Why is the ui option reqired though? Can there be another UI for swagger?

**Comment by imujjwal96** [comment]
There is `REDOC`, although we don't plan to integrate it anytime soon

**Comment by pri22296** [comment]
does REDOC also works using a swagger.json?

**Comment by imujjwal96** [comment]
Yes it does. Actually swagger follows the open api specification
