### ISSUE TITLE
Integrate API Blueprint with yaydoc

### ISSUE THREAD

**Issue by niranjan94** [fossasia/yaydoc#260]
### This is a
- [ ] Bug report
- [x] Feature request

Similar to #259 , we will need [api blueprint](https://apiblueprint.org/) support too. You could use [aglio](https://github.com/danielgtaylor/aglio) for generating documentation from an API Blueprint file. Aglio is also node.js based and has a programatic API. So it would be be easy to integrate with the project too.

**Comment by pri22296** [comment]
@niranjan94  , I found a sphinx extension https://github.com/tk0miya/sphinxcontrib-apiblueprint which can parse `apib` files and generate documentation. The advantage of this approach would be that the `theme` would be consistent across the whole site. Should we use this instead?

**Comment by niranjan94** [comment]
Sure ... No problem :)
