### ISSUE TITLE
set correct path for dependecies 

### ISSUE THREAD

**Issue by sch00lb0y** [fossasia/yaydoc#27]
path for mdinclude is set towards` /scripts` instead of `yaydoctemp/scripts` so it causing 
import error
```
Exception occurred:

  File "conf.py", line 177, in <module>

    import mdinclude

ImportError: No module named 'mdinclude'
```
[travis build log](https://travis-ci.org/sch00lb0y/tempCheck/builds/233525746)

**Comment by sch00lb0y** [comment]
I would like to work on this.
Thanks

**Comment by niranjan94** [comment]
@sch00lb0y the path is correct. The modules should be relative to this repo. `yaydoctemp` is just a temporary folder created. That shouldn't be hardcoded in the script. 

To fix this error, ensure the scripts are executed from the proper directory.

**Comment by sch00lb0y** [comment]
@niranjan94 I got it. i'll make change according to that.
Thanks

**Comment by pri22296** [comment]
But sphinx-quickstart needs to to be run from inside the temp dir. maybe we can expose the path to scripts directory as a template variable and pass it to sphinx-quickstart from generate.sh . That way the name yaydoctemp would only be used in generate.sh script.

**Comment by niranjan94** [comment]
@pri22296 can we not run `sphinx-quickstart` from the `yaydoc` directory pass the path to the `temp` directory as an argument instructing `sphinx-quickstart` to pick files from there

**Comment by niranjan94** [comment]
I specifically mean `sourcedir` in `sphinx-build [options] sourcedir builddir [filenames]`

**Comment by niranjan94** [comment]
I mean `projectdir` argument of `sphinx-quickstart [options] [projectdir]`

**Comment by pri22296** [comment]
@niranjan94 that would be best.

**Comment by pri22296** [comment]
@niranjan94 No matter where we call sphinx-quickstart from, the conf.py file will be generated in the temp directory, so it will still need to refer to yaydoctemp dir to call scripts it contains.
