### ISSUE TITLE
Review the design of yaydoc.yml

### ISSUE THREAD

**Issue by pri22296** [fossasia/yaydoc#271]
### This is a
- [ ] Bug report
- [ ] Feature request

### Current behaviour

We never had a discussion about the design of `.yaydoc.yml`, like the number of sections, names of sections and their position. As we have begun adding yaydoc to other projects, it would be tough to later change these things. So a final review should be made,

**Comment by pri22296** [comment]
@sch00lb0y @imujjwal96 Please give your inputs regarding this. You can see the current available options for `.yaydoc.yml` at https://github.com/fossasia/yaydoc#usage

**Comment by imujjwal96** [comment]
Does the position matter?

**Comment by pri22296** [comment]
@imujjwal96 By position I meant, whether a section should be a subsection of another section or kept as an standalone section.

**Comment by imujjwal96** [comment]
Should `apidocs` have been nested inside build?

**Comment by pri22296** [comment]
I don't know. What do you think?

**Comment by imujjwal96** [comment]
I am very bad at these 😂

**Comment by pri22296** [comment]
Haha, ok I propose the following changes

- Rename `doctheme` to `theme`
- Move `subproject` to `build`
- Create a new section `extras` which would be meant to hold features linking to external projects
- Keep `swagger`, `javadocs` to `extras`
- Maybe rename `publish` to `publishers`?

I would also like to rename `docpath`, but couldn't think of a decent name.

Please give your suggestions and your proposals and let's finalize on a proper design which looks good and isn't too verbose.

**Comment by imujjwal96** [comment]
- Makes sense
- Makes sense
- Makes sense
- Makes sense
- Why
- DOCROOT?

**Comment by pri22296** [comment]
Yeah, `publish` seems fine. `docroot` sounds similar to `docpath`. Any suggestion where it doesn't start with `doc`? I don't know, it just doesn't sounds good. I'd be ok with it though if you are.

**Comment by imujjwal96** [comment]
`source`
