### ISSUE TITLE
Add option to add RSS/XML feed of a blog to the site 

### ISSUE THREAD

**Issue by mariobehling** [fossasia/yaydoc#275]
The main site of FOSSASIA.org shows a blog feed on the website. Please implement that option in the even dev site as well. Add an option as a field to add a blog feed into the doc generator.

**Comment by imujjwal96** [comment]
@mariobehling the blog feed can be added to fossasia's sphinx theme but i don't think it would be feasible to add such in other sphinx themes

**Comment by imujjwal96** [comment]
Does this mean that the user will specify an rss field in the `yaydoc.yml` file and we will generate a carousel from it in the docs website?

**Comment by sch00lb0y** [comment]
@imujjwal96 you working on this?

**Comment by imujjwal96** [comment]
Nopsie
