### ISSUE TITLE
[Question] Is it mandatory to configure travis with language set to python?

### ISSUE THREAD

**Issue by imujjwal96** [fossasia/yaydoc#29]
In the documentation of this project, it is mentioned that I have to configure my travis as follow: 
![image](https://cloud.githubusercontent.com/assets/8245662/26210704/1b0baf38-3c0e-11e7-9dd2-3a5b37c791cb.png)

My question is, since I have a project in PHP which uses travis to build unit tests, I have to set PHP as my language. How would yaydoc integrate with my project then?

**Comment by niranjan94** [comment]
@imujjwal96 this is a good question.

AFAIK, it's _not_ mandatory to configure travis with language as python since every travis worker already has python installed (irrespective of what language you select). But I'm not sure which version of python will be available.

**Comment by pri22296** [comment]
@niranjan94 By default python 2.7 should be available. https://docs.travis-ci.com/user/languages/python/#Default-Python-Version
To use python 3:
- use sudo to install python3
- or, use addons as mentioned in this stackoverflow answer http://stackoverflow.com/a/37660551/4127836

**Comment by niranjan94** [comment]
@pri22296 thank you for the follow up. Could you update the README and add an alternative configuration for people who use a different language ?

**Comment by imujjwal96** [comment]
For reference: https://travis-ci.org/imujjwal96/prelimQuiz/jobs/233691751
