### ISSUE TITLE
Extending logfile generation to deployment

### ISSUE THREAD

**Issue by imujjwal96** [fossasia/yaydoc#290]
### This is a
- [ ] Bug report
- [x] Feature request

### Current behaviour

The LOGFILE is generated only for the logs of docs generation script.
### Expected behaviour

Extend this feature to the logs of Github deployment. This feature is needed as it becomes difficult to understand issues in those scripts without getting detailed logs for them.

**Comment by pri22296** [comment]
@imujjwal96 Might I suggest that you extend this issue to also unquiet all commands and send their logs to `LOGFILE`. I see no reason as to why **detailed logs** shouldn't be detailed.

**Comment by imujjwal96** [comment]
Thanks for emphasising on it. However, it was already planned :)

**Comment by imujjwal96** [comment]
@pri22296 @sch00lb0y  Should the logs for deployment processes be stored in the same file or different files

**Comment by pri22296** [comment]
I think different files would be better.
