### ISSUE TITLE
add CI support for sub projects.

### ISSUE THREAD

**Issue by sch00lb0y** [fossasia/yaydoc#297]
### This is a
- [ ] Bug report
- [x] Feature request

### Current behaviour

if subproject updated CI not pushing documentation to github pages
### Expected behaviour

make CI to push documentation to github pages if subprojects updated. 

### Steps to reproduce
1.
2.
3.

**Comment by imujjwal96** [comment]
Closed via PR https://github.com/fossasia/yaydoc/pull/318
