### ISSUE TITLE
Add docker image to dockerhub and autodeploy to Google Cloud with Kubernetes

### ISSUE THREAD

**Issue by mariobehling** [fossasia/yaydoc#300]
In order to make Yaydoc into a stable service we need to set up the infrastructure. Docker can help to do this more easily. Please signup on docker.com and join the yaydoc team. 

Create a docker file with Kubernetes and deploy automatically to Google cloud.

**Comment by imujjwal96** [comment]
I would like to work on this!

**Comment by mariobehling** [comment]
Great, please check out this to learn from it: https://github.com/fossasia/open-event-orga-server/blob/nextgen/kubernetes/travis/deploy-nextgen.sh

And read the conversations of the last few days on the SUSI AI server channel: https://gitter.im/fossasia/susi_server?at=596dc6970de4d2545e3b2ddd

**Comment by imujjwal96** [comment]
Thanks for the links @mariobehling. Will save a lot of time :D

**Comment by imujjwal96** [comment]
@pri22296  @sch00lb0y  Apparently, Google Cloud requires us to register using a credit card. My cards aren't valid for registration to google cloud so i'll not be able to work on it.

**Comment by pri22296** [comment]
@imujjwal96 I tried to register but my card is also invalid as per Google cloud. Maybe @sch00lb0y can try this once.

**Comment by sch00lb0y** [comment]
Even, I have this problem. HSBC and AXIS bank may work. but I don't have one. :sweat:

**Comment by niranjan94** [comment]
@imujjwal96 even debits cards work as long as international transactions are enabled. I can say for a fact that ICICI credit cards and debit cards work out-of-box.

**Comment by imujjwal96** [comment]
I have Maestro and Rupay cards and both are shown invalid in the registration. I guess they are limited to American Express, MasterCard and Visa.
