### ISSUE TITLE
Implement to show if the documentation is available on a repo (similar to travis)

### ISSUE THREAD

**Issue by mariobehling** [fossasia/yaydoc#302]
What kind of buttons could we show on project pages? E.g. could we have a button "yaydoc ok" and "yaydoc failed"?

Please propose and implement a way that projects can include a yaydoc button in their project.

**Comment by imujjwal96** [comment]
I would like to work on this.

In https://github.com/fossasia/yaydoc/pull/326, i have added a buildStatus key for repositories registered to Yaydoc. We can take that value and generate the status badge using https://shields.io/
