### ISSUE TITLE
Similarly to adding twitter feeds offer an option to add blog feeds

### ISSUE THREAD

**Issue by mariobehling** [fossasia/yaydoc#303]
Wordpress and other blog apps offer xml feeds. Please add an option to display the first section of blog posts through a feed in yaydoc e.g. http://blog.fossasia.org/tag/yaydoc/feed/ .

**Comment by imujjwal96** [comment]
I think this issue is fixed in PR https://github.com/fossasia/yaydoc/pull/299 @sch00lb0y  Can you confirm?

**Comment by sch00lb0y** [comment]
yeah it has been solved.
