### ISSUE TITLE
Add option to disable the CI in registered repository in Dashboard

### ISSUE THREAD

**Issue by sch00lb0y** [fossasia/yaydoc#305]
### This is a
- [ ] Bug report
- [x] Feature request

### Current behaviour

right now we can't disbale the CI 
### Expected behaviour

add a option to disable CI to the registered repository

### Steps to reproduce
1.
2.
3.

**Comment by imujjwal96** [comment]
@sch00lb0y Are you working on this? I can see  PR of issues raised after this. Also, i don't see a mention of this in your scrums.

**Comment by sch00lb0y** [comment]
@imujjwal96 I'll do this. I'll send a PR by tomorrow.

**Comment by imujjwal96** [comment]
Closed with PR #336
