### ISSUE TITLE
Tables do not get rendered for docs processed by recommonmark

### ISSUE THREAD

**Issue by sch00lb0y** [fossasia/yaydoc#311]
### This is a
- [x] Bug report
- [ ] Feature request

Tables not being part of the core commonmark spec aren't supported natively by recommonmark. recommonmark currently does not provide an api to create extensions. So currently table aren't rendered if present in a markdown file processed by recommonmark

**Comment by sch00lb0y** [comment]
@pri22296 can you check this?

**Comment by pri22296** [comment]
It seems recommonmark doesn't support Headings as list elements. As a workaround could you edit this line https://github.com/fossasia/open-event-android/blame/a01dff63e7d1e858489583c42a8c6f64029844f5/docs/apk-generator.md#L57 and https://github.com/fossasia/open-event-android/blame/a01dff63e7d1e858489583c42a8c6f64029844f5/docs/apk-generator.md#L67 so that the numbers are part of the heading and try if the error still happens.

**Comment by sch00lb0y** [comment]
@pri22296 will check and let you know

**Comment by pri22296** [comment]
@sch00lb0y Any update on this?

**Comment by sch00lb0y** [comment]
@pri22296 it is working. but the table is not rendering properly here http://yaydoc.herokuapp.com/preview/rbalajis25@gmail.com/aedc5d53-cf14-43f0-8cd2-8ec0db5d0c62_preview/INSTALLATION_LOCAL.html https://github.com/sch00lb0y/open-event-webapp/blob/development/docs/INSTALLATION_LOCAL.md . I tried a lot but not able to find.

**Comment by imujjwal96** [comment]
The table is not rendering because the markdown is incorrect

**Comment by sch00lb0y** [comment]
``` 
Component  | Name/Flavour | Minimum Version 
------------|--------------|----------------           
  OS        | Mac/Windows/Linux | Any 
 Node.js    | None  | v4.0 (or above) 
 Browser    | Firefox/Chrome/Safari | 21+/11+/9+ 
```
@imujjwal96 I'm using this still  table not rendering. can you check what went wrong?

**Comment by imujjwal96** [comment]
```
| Component  | Name/Flavour | Minimum Version |
|------------|--------------|----------------|
| OS        | Mac/Windows/Linux | Any |
| Node.js    | None  | v4.0 (or above) |
| Browser    | Firefox/Chrome/Safari | 21+/11+/9+ |
```
Try this!

**Comment by sch00lb0y** [comment]
I have tried but then still not rendering :cry: :cry:

**Comment by pri22296** [comment]
Ok, It seems tables aren't part of the core commonmark spec. Check this thread for more info https://github.com/rtfd/recommonmark/issues/3

**Comment by imujjwal96** [comment]
@pri22296 @sch00lb0y Is this issue solved?

**Comment by pri22296** [comment]
I think it was. @sch00lb0y can you confirm?

**Comment by sch00lb0y** [comment]
yeah solved. but table not rendering. close this ?

**Comment by imujjwal96** [comment]
@pri22296 facing this issue in loklak_server as well! is there a workaround?

**Comment by pri22296** [comment]
AFAIK no for now. Maybe use an html table for now?

**Comment by imujjwal96** [comment]
@pri22296 Please edit this issue's description
