### ISSUE TITLE
Cannot have index.rst file in the root directory.

### ISSUE THREAD

**Issue by imujjwal96** [fossasia/yaydoc#32]
When I attempted to generate documentation of my project through yaydoc, there was an issue that when the index.rst file is kept in the root directory setting DOCPATH as `/` and `./` didn't work.
Eventually had to copy the index.rst file in `docs` folder.

**Comment by pri22296** [comment]
@imujjwal96 I'll have a look at it.

**Comment by pri22296** [comment]
@imujjwal96 I believe the cause of this error is that we are creating our temporary directories in root itself. so if the DOCPATH is also specified as root, generate.sh copies everything including the entire virtual environment as well inside yaydoctemp. I think creating the temporary directories outside the root should solve this issue.
