### ISSUE TITLE
DOCURL is not passed to ghpages_deploy.sh

### ISSUE THREAD

**Issue by imujjwal96** [fossasia/yaydoc#337]
### This is a
- [x] Bug report
- [ ] Feature request

### Current behaviour

| Environment variables in generate script. | Environment variables in ghpages_deploy script |
|-------|----------|
| ![image](https://user-images.githubusercontent.com/8245662/28754893-694b9cc0-756c-11e7-9d8e-8524df9656a0.png) | ![image](https://user-images.githubusercontent.com/8245662/28754920-b52cee8c-756c-11e7-8fc8-36b7f26dfc85.png) |

Also, since base doesn't exist in ghpages_deploy it does not execute

**Comment by imujjwal96** [comment]
@pri22296 Take a look

**Comment by pri22296** [comment]
@imujjwal96 How did you obtain the second image? If the script never executed, how did you got it's output?

**Comment by imujjwal96** [comment]
I made changes
![image](https://user-images.githubusercontent.com/8245662/28754968-21bc537a-756e-11e7-95ef-c1d5a5f8d718.png)
Thought it was a minor bug.

**Comment by pri22296** [comment]
@imujjwal96 This is because config.py cannot find a `.yaydoc.yml` file in the current working directory. Hence you can see that all values in the `deploy_scripts` are actually the defaults. I guess the best solution would be to copy the `.yaydoc.yml` file somewhere from the generate script so that we can reference it from the deploy scripts.

**Comment by imujjwal96** [comment]
@pri22296 will you send a separate PR or should i adjust it in an existing PR?

**Comment by pri22296** [comment]
If it's urgent, please adjust it in an existing PR.

**Comment by imujjwal96** [comment]
Not that urgent. Please submit a new PR :)

**Comment by pri22296** [comment]
No. not at all. Sending a PR now. 😄
