### ISSUE TITLE
Error when deploying to ghpages using one-time deployment

### ISSUE THREAD

**Issue by pri22296** [fossasia/yaydoc#340]
### This is a
- [x] Bug report
- [ ] Feature request

### Current behaviour

The following message is displayed

`Cipher data must be a string or a buffer`

**Comment by pri22296** [comment]
@imujjwal96 Please look into this

**Comment by imujjwal96** [comment]
@pri22296  that is fixed in #334

**Comment by pri22296** [comment]
@imujjwal96 I'll close this after confirming when #334 gets merged.

**Comment by imujjwal96** [comment]
In fact, the crypter function in that file was added there while working on a solution to this :)

**Comment by pri22296** [comment]
@imujjwal96 Although that error is now fixed, documentation doesn't seem to be really getting pushed to gh-pages branch. The webUI shows documentation pushed successfully, but last commit on my gh-pages branch is still 9 days earlier. Can you please take a look at this?

**Comment by imujjwal96** [comment]
OK! I'll check

**Comment by imujjwal96** [comment]
Fixed by PR https://github.com/fossasia/yaydoc/issues/343
