### ISSUE TITLE
show status of the build on PR

### ISSUE THREAD

**Issue by sch00lb0y** [fossasia/yaydoc#349]
### This is a
- [ ] Bug report
- [x] Feature request

### Description
show the status of the build on each PR using GitHub status API

### Steps to reproduce
1.
2.
3.

**Comment by imujjwal96** [comment]
Can you please explain what the expected behaviour is?

**Comment by sch00lb0y** [comment]
commenting preview link to show the preview of the documentation when the user sends PR. (similar to CodeCov report)

**Comment by imujjwal96** [comment]
It will unnecessarily waste our resources. I do not think we should implement it. But that's only my opinion. I would request you to consult mentors about this feature.

**Comment by niranjan94** [comment]
Not necessary. This is a documentation project. And documentations are easily readable from the code itself. Instead of this, what you could do is, show status updates via github's status api. Like Travis status you can have build status

**Comment by imujjwal96** [comment]
Closed via PR https://github.com/fossasia/yaydoc/pull/318
