### ISSUE TITLE
Add option to add disqus comments in the generated docs

### ISSUE THREAD

**Issue by pri22296** [fossasia/yaydoc#350]
### This is a
- [ ] Bug report
- [x] Feature request

### Expected behaviour

Users would be able to add disqus comments on any page using a simple directive.

### Steps to reproduce
1.
2.
3.

**Comment by mariobehling** [comment]
Description of this issue is incomplete and PR and what is available is very low priority and out of scope. We don't need a discussion in documentation. Please do focus on getting documentation up and running. Please get this project working now.
