### ISSUE TITLE
Allow users to update sub projects registered to a master project 

### ISSUE THREAD

**Issue by sch00lb0y** [fossasia/yaydoc#378]
### This is a
- [ ] Bug report
- [x] Feature request

### Current behaviour

User can add sub project only while registering sub project.
### Expected behavior

user should have the option to add or remove sub project after registering the project.

### Steps to reproduce
1.
2.
3.

**Comment by imujjwal96** [comment]
The origin title was very vague. Reading the description, I think the updated title is slightly more clear.
