### ISSUE TITLE
Images are not included for subprojects.

### ISSUE THREAD

**Issue by pri22296** [fossasia/yaydoc#382]
### This is a
- [x] Bug report
- [ ] Feature request

### Current behaviour

For subprojects, images aren't displayed.

### Expected behaviour

Images should get displayed properly.

### Steps to reproduce
1. Go to https://yaydoc.herokuapp.com/
2. Generate docs for susi_server repo
3. Visit any sub-projects. Images would not be displayed.

It should be noted that the repo builds properly when it the main project.

**Comment by imujjwal96** [comment]
Closethis?
