### ISSUE TITLE
Error on clicking on latest logs

### ISSUE THREAD

**Issue by pri22296** [fossasia/yaydoc#385]
### This is a
- [x] Bug report
- [ ] Feature request

### Current behaviour

Error message: Cannot read property 'ref' of undefined

### Expected behaviour

Latest logs should be shown

### Steps to reproduce
1. Go to https://yaydoc.herokuapp.com
2. Check the build logs of yaydoc itself
3. click on latest logs

**Comment by pri22296** [comment]
@imujjwal96 Please check this

**Comment by imujjwal96** [comment]
The content we show now, along with the latest log was not there in the database when the logs were being created before. Hence, we'll have to delete those logs

**Comment by pri22296** [comment]
@imujjwal96 close this then?

**Comment by imujjwal96** [comment]
Sure!
