### ISSUE TITLE
add fossasia theme to templates

### ISSUE THREAD

**Issue by sch00lb0y** [fossasia/yaydoc#39]
currently we don't have fossasia theme in yaydoc custom templates. so add fossasia theme and theme path in conf.py_t

**Comment by sch00lb0y** [comment]
i'll work on this.
Thanks

**Comment by pri22296** [comment]
@sch00lb0y Currently, yaydoc can install custom themes from PyPI. Instead of hardcoding fossasia theme in conf.py_t, we should add the ability to install themes from a url or something like that.

**Comment by sch00lb0y** [comment]
if it that case we have publish theme to PyPI. we already cloning yaydoc in travis. if we download theme from url . it increase the build time. anyway we doing this only for fossasia .

**Comment by pri22296** [comment]
Yeah but I don't think we should couple yaydoc and the theme. Yaydoc and the fossasia's theme should be usable without each other also.

**Comment by sch00lb0y** [comment]
your point also valid. let's ask some suggestion from @imujjwal96 @niranjan94
