### ISSUE TITLE
Build Log is too verbose

### ISSUE THREAD

**Issue by pri22296** [fossasia/yaydoc#40]
Although warnings and errors from sphinx is useful as it provides debug info about the docs, we can decrease the verbosity of other steps such as

- package installation done via pip
- git rm in gh-pages dir
- log from sphinx which are not warnings or errors

Sample build log - https://travis-ci.org/pri22296/testYaydoc/builds/234470830

**Comment by pri22296** [comment]
I have reduced the verbosity of many steps in our build process which has lead to more clean build logs. But I am not able to remove the multiple instances of  `InsecurePlatformWarning` . According to [this stackoverflow answer](https://stackoverflow.com/a/29099439/4127836) we need to upgrade the python version but I am not able to use python3 in non-python travis configuration. Any suggestions? @niranjan94  @imujjwal96 @sch00lb0y 

Here is the build log after my changes-
https://travis-ci.org/pri22296/testYaydoc/builds/234922778

**Comment by sch00lb0y** [comment]
instead of virtual env why don't you try `apt install python3`

**Comment by pri22296** [comment]
The virtualenv is used to make pip install work. pip install fails with a permission error on a non-python configuration. refer https://travis-ci.org/imujjwal96/prelimQuiz/jobs/233691751
I'm trying to setup our script in such a way that it works on different python versions but as we can see, virtualenv creation fails on python 3.2. should we ignore 3.2?
