### ISSUE TITLE
 Update the UI of the homepage

### ISSUE THREAD

**Issue by imujjwal96** [fossasia/yaydoc#433]
### This is a
- [ ] Bug report
- [x] Feature request

### Current behaviour

Currently UI of App Generator is lacking Top navbar, Menu item and Version deployment info
### Expected behaviour

* Add top bar similar to Open Event frontend
* Add menu like Google/Susper on the top right corner (http://susper.com/)
* Add Version deployment info to the bottom like http://staging.loklak.org

**Comment by gabru-md** [comment]
Can you please tell me what are all the elements that are required to be placed on the top-bar and the Menu bar ? Since I would like to work on this issue and it would be helpful if you could let me know.
Thanks.

**Comment by imujjwal96** [comment]
@gabru-md Please refer this PR https://github.com/fossasia/open-event-webapp/pull/1465

**Comment by imujjwal96** [comment]
Here's the expected output: https://opev-webgen-dev.herokuapp.com

**Comment by gabru-md** [comment]
Thank you ! I would like to work on this.

**Comment by jajodiaraghav** [comment]
Hi @gabru-md 
Are you working on this one, or can I take this?

**Comment by gabru-md** [comment]
Yes I am working on it. Please give me some time I'll be working on it soon

**Comment by imujjwal96** [comment]
@gabru-md What's the update?

**Comment by jajodiaraghav** [comment]
It's been more than a month. I think it should be made open for claiming.

**Comment by imujjwal96** [comment]
Consider it open! @jajodiaraghav

**Comment by jajodiaraghav** [comment]
Awesome! Claiming 🚀 

Will send a PR soon
