### ISSUE TITLE
use gzip to serve web pages

### ISSUE THREAD

**Issue by sch00lb0y** [fossasia/yaydoc#434]
### This is a
- [ ] Bug report
- [x] Feature request
use `compression` middleware to serve web pages in gzip to increase the performance

**Comment by yukiisbored** [comment]
This is not something you do from yaydoc's side. This is something you do on the web server.

**Comment by imujjwal96** [comment]
@yukiisbored have a look at this. https://expressjs.com/en/advanced/best-practice-performance.html#use-gzip-compression

It is known that the core change has to be made server side, but even if we do that, it'd not work without including a middleware inside the application

**Comment by yukiisbored** [comment]
@imujjwal96 That documentation is for people who doesn't use a reverse proxy.

**Comment by imujjwal96** [comment]
Oh! Then i guess we can close this.
