### ISSUE TITLE
yaydoc.org is down - 502

### ISSUE THREAD

**Issue by aviaryan** [fossasia/yaydoc#436]
### This is a
- [x] Bug report
- [ ] Feature request

### Current behaviour

yaydoc.org shows 502.
![screen shot 2017-09-24 at 6 35 38 pm](https://user-images.githubusercontent.com/4047597/30782864-34e6d596-a157-11e7-855d-585f29866dc1.png)

### Expected behavior

The website should work.

----

I would like to work on this if possible.

**Comment by sch00lb0y** [comment]
@aviaryan actually our deployment is down. FYI We are planning to migrate the deployment from gcp to bluemix. are you working on this?

**Comment by aviaryan** [comment]
@sch00lb0y Is bluemix free? Do we have a shared account on bluemix where this should be hosted?

**Comment by sch00lb0y** [comment]
@aviaryan we don't have any shared account. @mariobehling told that Mario can get us vouchers to run deployment. please check this gitter channel for further info https://gitter.im/fossasia/yaydoc
