### ISSUE TITLE
LinkedIn icon redirecting to a broken url

### ISSUE THREAD

**Issue by Dishebh** [fossasia/yaydoc#461]
### This is a
- [x] Bug report
- [ ] Feature request

### Current behaviour

Currently, LinkedIn social icon is redirecting to a non existing web page, so it seems.
### Expected behaviour

It should redirect to the FOSSASIA group at LinkedIn.

### Steps to reproduce
1. Go to the [website](https://www.yaydoc.org)
2. Scroll to the bottom and click on the LinkedIn icon

###Screenshots of the issue
![Screenshot from 2019-12-16 21-53-04](https://user-images.githubusercontent.com/43489708/70935355-03291b00-2066-11ea-9107-d876cdba2eab.png)

### Would you like to work on the issue?
Yes

**Comment by Aaryan-kapur** [comment]
Hey can i take this up!?

**Comment by Dishebh** [comment]
Sure, go ahead

**Comment by bapelindo** [comment]
hello, can i take this too bro?

**Comment by pkspyder007** [comment]
@Aaryan-kapur  are you still working on it. I would like to fix this.

**Comment by ssd71** [comment]
This is an issue in the FOSSASIA sphinx theme, I don't believe it can be fixed from this repository :)
