### ISSUE TITLE
use a python script instead of shell script for generation of docs

### ISSUE THREAD

**Issue by pri22296** [fossasia/yaydoc#51]
This will have two major advantages

- The python script would be cross platform.
- It would be easy to perform some logic driven tasks in a python script as compared to a shell script.

**Comment by sch00lb0y** [comment]
sound great but if we do once again with python it'll be duplication of work. further automation work we'll do in python and we'll execute from shell or else we'll port the entire shell script to python but we have to test a lot . it takes bit time and also it we'll be ended up in executing shell  sub process from python

**Comment by pri22296** [comment]
yeah, i agree we'll have to port the script but in the long run I think it will be beneficial.
Also, not all commands will need to be executed using `subprocess` module. The `os` module provides a lot of utility functions we can use. The cross-platform nature of the script in itself would be very beneficial.

**Comment by niranjan94** [comment]
@pri22296 this is a good idea. Go for it. This will also be beneficial for later extension.

**Comment by yukiisbored** [comment]
Not a good idea. Python scripts are harder to manager over regular shell scripts. Since most of the stuff we do is using userland utilities such as `git`, `sphinx`, etc. There's no good reason to use Python scripts. Sure on one hand it makes it more "python-nic" since Sphinx is written in Python but that's not everything you're doing (like the fact this project relies heavily on using `git`)

**Comment by pri22296** [comment]
@yukiisbored I totally agree that we should not over-engineer stuff. but similar to my query at #56 , to support other CI, we would have to maintain multiple scripts(a shell script, a powershell script, etc). Or are we targeting here only projects using linux based CIs? If that is the case, ofcourse a shell script would be better.

**Comment by yukiisbored** [comment]
@pri22296 Well since most CI are Linux anyway (only Appveyor that I know of that uses Windows). Just use Shell scripts.

**Comment by imujjwal96** [comment]
Close this?

**Comment by pri22296** [comment]
close this?

**Comment by jig08** [comment]
@niranjan94 @yukiisbored  Views on this pls.
IMO, We should stick to Shell Scripts ..
