### ISSUE TITLE
Setup documentation for yaydoc itself in gh-pages branch

### ISSUE THREAD

**Issue by mariobehling** [fossasia/yaydoc#55]
Please create a gh-pages branch using CNAME yaydoc.fossasia.org and automatically deploy the documentation for the project itself in the gh-pages branch.

**Comment by imujjwal96** [comment]
I don't think we have the access to create a branch in this repository. (We'll have to do that manually for the script to work)
Also for the automatic deployment, we'll need to set environment variables in Travis

**Comment by pri22296** [comment]
We don't need to create a gh-pages branch manually. PR #38 which was merged added ability to create a gh-pages branch if not already present. After the appropriate environment variables are set, the docs should be deployed automatically.

**Comment by imujjwal96** [comment]
Oh! My bad.

**Comment by imujjwal96** [comment]
Following Environment Variables with these values must be set

| Environment Variable | Value                                       |
|----------------------| ------------------------------------------------- |
| AUTHOR               | FOSSASIA   |
| DOCPATH              | docs/ |
| DOCURL               | yaydoc.fossasia.org |
| GITURL               | https://\<username\>:\<your-github-personal-token\>@github.com/fossasia/yaydoc.git |
| PROJECTNAME          | Yaydoc                              | NONE * |
| VERSION              | development                           | NONE * |

**Comment by mariobehling** [comment]
@imujjwal96 Please add the variables to travis.yml and add a new deployment key to the settings following the approach mentioned in this document: https://gist.github.com/domenic/ec8b0fc8ab45f39403dd#get-encrypted-credentials
