### ISSUE TITLE
Use Travis' deploy to Github pages feature

### ISSUE THREAD

**Issue by yukiisbored** [fossasia/yaydoc#56]
Travis already has it's own deployment system which you can use to deploy stuff to GitHub pages on the same/different repository. I recommend using this over doing this inside the `script` section, due to the fact you're using someone's GitHub token and it should be handled carefully.

**Comment by pri22296** [comment]
@yukiisbored But wouldn't that couple yaydoc to travis. what if a project uses another CI?

**Comment by imujjwal96** [comment]
From what I could understand, @yukiisbored
Do we have to use the deploy command in travis configuration, as in https://github.com/loklak/loklak_server/blob/development/.travis.yml

**Comment by mariobehling** [comment]
@pri22296 Using travis is sufficient for now to get us started and proceed quickly.

**Comment by pri22296** [comment]
@mariobehling But the deploy to gh pages is already implemented in the script. From what i understand, what this Issue suggests is to replace it and use travis's deploy feature instead. But we would ultimately need to use our implementation when generating via the web-ui.

**Comment by mariobehling** [comment]
@pri22296 If this is already implemented then good. Closing it therefore.
