### ISSUE TITLE
Separating Documentation generation and Github Pages deployment

### ISSUE THREAD

**Issue by imujjwal96** [fossasia/yaydoc#59]
### This is a
- [ ] Bug report
- [x] Feature request

### Current behaviour

There is a single script for generating documents and publishing them to gh-pages branch. 
### Expected behaviour

Separating both these processes would enable many possibilities, including FTP deployment et al.

**Comment by imujjwal96** [comment]
@mariobehling @niranjan94 @jig08 @yukiisbored
@sch00lb0y @pri22296 

Does this make sense?

**Comment by imujjwal96** [comment]
Since the project is intended to be limited to only publish documents in gh-pages. I think this separation is no longer needed. 
Close this?

**Comment by pri22296** [comment]
I think we should proceed with this. gh-pages or not, it's good idea to seperate things which are inherently not connected. It would also help with any later extension.
