### ISSUE TITLE
config values AUTHOR, VERSION, PROJECTNAME should be optional

### ISSUE THREAD

**Issue by pri22296** [fossasia/yaydoc#63]
### This is a
- [ ] Bug report
- [x] Feature request

### Current behaviour
build fails if AUTHOR, VERSION and PROJECTNAME is not specified.

### Expected behaviour
sensible default values should be used if they are not specified. we already have the GITURL in a very specific format. we can also parse the AUTHOR and PROJECTNAME from that as default. Even DOCPATH could have a default value such as `docs`.

**Comment by jig08** [comment]
@pri22296 Legit. Are you working on this ?

**Comment by pri22296** [comment]
@jig08 If PR #84 is merged, `""` would be used as fallback. So not working on it.

**Comment by pri22296** [comment]
This was fixed by #84
