### ISSUE TITLE
Exception occurs when publishing docs via yaydoc

### ISSUE THREAD

**Issue by imujjwal96** [fossasia/yaydoc#66]
### This is a
- [x] Bug report
- [ ] Feature request

### Current behaviour

When I try to build documentation of my project using yaydoc, i get an Exception in the travis log

    Exception occurred:

    File "/home/travis/build/imujjwal96/[secure]/yaydocvenv/local/lib/python2.7/site-packages/pypandoc/__init__.py", line 325, in _convert_input

    'Pandoc died with exitcode "%s" during conversion: %s' % (p.returncode, stderr)

    RuntimeError: Pandoc died with exitcode "83" during conversion: pandoc: Error running filter filters/yml_filter.py:

    Could not find executable 'filters/yml_filter.py'.

https://travis-ci.org/imujjwal96/prelimQuiz/jobs/238663584

### Expected behaviour

Documentation should be build and published successfully.

### Steps to reproduce
1. Add travis config from yaydoc README to project's .travis.yml file and commit.
2. Setup environment variables in yaydoc

**Comment by imujjwal96** [comment]
@sch00lb0y Something because of your fix to issue #57 ?

**Comment by imujjwal96** [comment]
Quoting @sch00lb0y 

> Your bug is not happening of the #57 . The bug is rising because pandoc is not installed in your travis. I guess pandoc is not installing because of the virtual env python. please raise that as a separate issue.

@sch00lb0y @pri22296 Guess this is also an issue specific to having a base language other than python.

**Comment by pri22296** [comment]
@imujjwal96 I am afraid that conclusion is wrong about pandoc not being installed. Pandoc is clearly installed as evident from the error message. The error seems to be in the path that is being used to call the yml_filter.

**Comment by imujjwal96** [comment]
Cannot comment on Python specific errors right now.

Also i tried it with setting python as the base language and it still fails. https://travis-ci.org/imujjwal96/mydoc/builds/238774136

**Comment by pri22296** [comment]
This was solved by PR #67 . close this?

**Comment by imujjwal96** [comment]
@pri22296 I hope you won't mind if I test yaydoc by deploying it once.

Posted in the wrong thread before :P

**Comment by imujjwal96** [comment]
Tested, fixed :+1:

**Comment by imujjwal96** [comment]
Tested, fixed :+1:
