### ISSUE TITLE
Docs are published to gh-pages even after a failed documentation generation

### ISSUE THREAD

**Issue by imujjwal96** [fossasia/yaydoc#68]
### This is a
- [x] Bug report
- [ ] Feature request

### Current behaviour

I tried to test yaydoc. Apparently, there was a bug in it which lead to a failure in documentation generation. Even after an exception was raised in the travis logs, the script continued its execution and pushed the erroneous docs.
### Expected behaviour

The execution of the script should stopped in such a case.

### Travis log
Link: https://travis-ci.org/imujjwal96/prelimQuiz/jobs/238663584

#### Snapshot
![image](https://cloud.githubusercontent.com/assets/8245662/26724123/6ee535fe-47b5-11e7-9eaf-41632ff4d099.png)

**Comment by imujjwal96** [comment]
I will try to solve it.

**Comment by imujjwal96** [comment]
Researching about it, I came across [Build Stages - Travis](https://docs.travis-ci.com/user/build-stages)

@mariobehling @niranjan94 @sch00lb0y @pri22296 
I think this approach will work, but don't know if it will be efficient.
What do you think? 'tis a fine approach or should we tweak the script?

**Comment by sch00lb0y** [comment]
if we modify the travis. installation of script will be hard for the user. i think we can solve this with simple if case

**Comment by imujjwal96** [comment]
i don't think issues like #66 will be solved by conditional statement. I might be wrong though

**Comment by pri22296** [comment]
@imujjwal96 I agree with @sch00lb0y here. using a travis specific feature would prevent us from generalizing Yaydoc for other CIs. I think this should be solved using conditional statements in the shell script itself.

**Comment by imujjwal96** [comment]
Understandable.
~But then also, we might even develop our own Github Integration.~
