### ISSUE TITLE
Test and Document generation of Documentation using various CIs

### ISSUE THREAD

**Issue by imujjwal96** [fossasia/yaydoc#73]
### This is a
- [ ] Bug report
- [x] Feature request

### Current behaviour

We've only documentation the usage of yaydoc by configuring TravisCI
### Expected behaviour

Yaydoc shouldn't be limited to TravisCI. Using it via other CI must also be documented.

**Comment by imujjwal96** [comment]
I think the first step would be to list all the CI's and create separate issue for each CI.
We can then distribute them among ourselves to work concurrently.
makes sense? @sch00lb0y @pri22296

**Comment by mariobehling** [comment]
This is low priority. We need the project to work with Travis for now. That is sufficient. There are hardly any features in this project. Focus on developing the actual project, please.
