### ISSUE TITLE
Automatic deployment of documents generated by yaydoc to Heroku

### ISSUE THREAD

**Issue by imujjwal96** [fossasia/yaydoc#74]
### This is a
- [ ] Bug report
- [x] Feature request

### Current behaviour

The project is currently limited to deploying web pages to Github Pages
### Expected behaviour

Extending that to deploy documentations to Heroku

**Comment by imujjwal96** [comment]
I'd be working on it.

**Comment by mariobehling** [comment]
Yes, sure.
