### ISSUE TITLE
Add new line to code block

### ISSUE THREAD

**Issue by sch00lb0y** [fossasia/yaydoc#79]
### This is a
- [x] Bug report
- [ ] Feature request

### Current behaviour

if there is no new line before code block pandoc not converting md to rst properly.
### Expected behaviour

new line has to be inserted if no new line before codeblock

### Steps to reproduce
1. add new line in the filter

**Comment by sch00lb0y** [comment]
since pandoc taking the whole string as a node we won't be able to modify the filter further so we have to use our custom parser. any view @pri22296 @imujjwal96

**Comment by pri22296** [comment]
@sch00lb0y I am not able to reproduce this error locally. could you share the document you are testing on?

**Comment by sch00lb0y** [comment]
@pri22296 i'm resolving your finding

> In order to convert to rst properly, the md file should have the following properties. This list is not exhaustive.

>    All headings must have a blank line before them.
>   Code blocks should begin from beginning of line
>    code block to render yml files should be named yaml not yml
>    A list must be preceded by a blank line

**Comment by pri22296** [comment]
No point there seems to suggest that that code blocks must be preceded by a blank line. That point is about headers not code-blocks.

**Comment by pri22296** [comment]
@sch00lb0y I did some research about this issue. It seems by default pandoc uses it's own flavour of markdown which add these conditions such as headings requiring blank lines as evident at jgm/pandoc#467 . But pandoc also allows us to use a different flavour of markdown such as of Github's. Maybe we can just allow the user to change the flavour based on some environment variables. That would solve many of these issues. what do you think?

**Comment by sch00lb0y** [comment]
yeah , sounds cool i'll make changes according to that

**Comment by pri22296** [comment]
@sch00lb0y close this?

**Comment by sch00lb0y** [comment]
yeah
