### ISSUE TITLE
Read config values from a configuration file instead of using environment variables

### ISSUE THREAD

**Issue by pri22296** [fossasia/yaydoc#8]
Currently, If a user decides to use say  Circle CI instead of Travis CI, currently they would need to setup all the environment variables again.

**Comment by niranjan94** [comment]
@pri22296 somethings, such as `GITURL` cannot be kept in a config file on the repo since it contains sensitive information. (Github access token). 

The rest can be kept in a config file if required. Let us give the user both options.

**Comment by pri22296** [comment]
@niranjan94 Yeah, that would be best. But if the user specifies a conflicting setting on both config file and as a environment variable, which one should be given precedence?

**Comment by niranjan94** [comment]
Environment variable should take precedence

**Comment by niranjan94** [comment]
But, i don't feel this is a higher priority right now. We need a proper script and theme first.

**Comment by imujjwal96** [comment]
@pri22296 The last travis buid errored. Please have a look at the travis build log
  https://travis-ci.org/fossasia/yaydoc/builds/242468285

**Comment by pri22296** [comment]
close this?
