### ISSUE TITLE
Add ability to create documentation from diffrent input format

### ISSUE THREAD

**Issue by sch00lb0y** [fossasia/yaydoc#81]
### This is a
- [ ] Bug report
- [x] Feature request

### Current behaviour

Right now sphinx support only to create documentation from markdown
### Expected behaviour

Make feature to create documetation from several input format like github markdown, latex, ...

### Steps to reproduce
1. add input format to pandoc

**Comment by pri22296** [comment]
@sch00lb0y could you make this issue more clear? what kind of input formats are we talking about?
