### ISSUE TITLE
Error while deploying documentation using CircleCI

### ISSUE THREAD

**Issue by imujjwal96** [fossasia/yaydoc#82]
### This is a
- [x] Bug report
- [ ] Feature request

### Current behaviour

![image](https://cloud.githubusercontent.com/assets/8245662/26835627/5639f668-4af6-11e7-8096-7eb75a8b86fa.png)

Link: https://circleci.com/gh/imujjwal96/mydoc/11

circle.yml
![image](https://cloud.githubusercontent.com/assets/8245662/26835725/8d164b8c-4af6-11e7-93c0-0921ef66dbe2.png)

After we run sphinx-quickstart, a folder named Bhardwaj is created in Circle CI.
The same doesn't happen in Travis CI

**Comment by imujjwal96** [comment]
Apparently, the reason for this error was the I had added Environment Variable 
AUTHOR Ujjwal Bhardwaj
A potential bug in sphinx-quickstart and may also occur in other CI as well.

PS:- The following error doesn't occur in Travis

**Comment by mariobehling** [comment]
I think Circle-CI is not a priority now. Travis is sufficient. Anyways, it is not our long-term goal to integrate with Circle-CI. Closing it therefore due to low priority.

**Comment by imujjwal96** [comment]
Actually this issue wasn't related to CircleCI per se. It was more related to a bug in the Sphinx command that we have in our script. Merging #84 fixes this.

**Comment by pri22296** [comment]
Yeah, I agree with @imujjwal96 . This was actually a bug in our script.
