### ISSUE TITLE
Fix codacy Issues

### ISSUE THREAD

**Issue by pri22296** [fossasia/yaydoc#86]
There are various issues from before pylint was integrated. They should be fixed.

**Comment by sch00lb0y** [comment]
yeah we'll remove unwanted lints in the confic

**Comment by pri22296** [comment]
Some of the issues are genuine. They should also be fixed.

**Comment by sch00lb0y** [comment]
@pri22296 @imujjwal96 please list all the lint which you consider as unwanted. we'll remove those lints

**Comment by pri22296** [comment]
For now I would suggest

- disable `import-error`
- decrease `too-few-public-method` threshold to 1
- increase `too-many-public-methods` threshold to a suitable value
