### ISSUE TITLE
Allow usage via access token as a fallback on failure to clone via SSH url.

### ISSUE THREAD

**Issue by pri22296** [fossasia/yaydoc#89]
### This is a
- [ ] Bug report
- [x] Feature request

### Current behaviour

Since #87 was merged, the old behaviour of using an access token with an https url was removed.

### Expected behaviour

Yaydoc should try to clone via SSH url and on failure use the value of GITURL as fallback.

**Comment by imujjwal96** [comment]
I have one doubt. When we build the WebUI, can we expect the user to submit his access token in the form? Don't you think submitting such token would be skeptical?

**Comment by niranjan94** [comment]
@imujjwal96 for the web UI, use won't be submitting access token via a form. We'll use github's OAuth authentication flow to enable users to allow access to our application and we'll obtain a repo token via that. See open-event-webapp

**Comment by mariobehling** [comment]
@imujjwal96 We talked about it a few times now, could you please have a look into the actual codebase of the Open Event generators? You seem to come up with more and more questions that have already been solved elsewhere. 

We have really talked about this many times now.

I urge you, please check out the Open Event generators and if there are questions feel free to ask in those channels.

**Comment by imujjwal96** [comment]
That means there is no need to implement this.
@pri22296 Close this

**Comment by niranjan94** [comment]
@imujjwal96 @pri22296 this is still required. Via the OAuth flow we'd still be getting an access token at the end from GitHub which we should be able to consume. 

@pri22296 please proceed with this.
