### ISSUE TITLE
Directory is not cleaning up if any failure happens

### ISSUE THREAD

**Issue by sch00lb0y** [fossasia/yaydoc#92]
### This is a
- [x] Bug report
- [ ] Feature request

### Current behavior

if any failure happens in the middle of execution, files created by the script is not cleaning up
### Expected behavior

files created by script should be deleted even if any failure happens

### Steps to reproduce
1. 
2. 
3.

**Comment by imujjwal96** [comment]
Just to be clear, the **Steps to reproduce** heading is not for the work that you'll perform to solve the issue. Instead, it is to mention the steps that were performed before the error occurred.
